services:
    frontend:
        image: ${GHCR_IMAGE}:latest

        container_name: tablebooking-frontend

        ports:
            - '3000:3000'

        env_file:
            - .env

        restart: unless-stopped
