import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NextAuthWrapper from '@/shared/library/next.auth.wrapper';
import { ReactQueryProvider } from '@/shared/library/react-query';
import { Toast } from '@heroui/react';
import AppInit from './AppInit';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="vi">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ReactQueryProvider>
                    <NextAuthWrapper>
                        <AppInit>{children}</AppInit>
                        <Toast.Provider placement="top end" />
                    </NextAuthWrapper>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
